# Generated by Django 4.2.6 on 2023-11-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Device name')),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4 address')),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceAnalyzeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='Analysis result')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'IoT Network Analysis',
                'verbose_name_plural': 'IoT Network Analysis',
            },
        ),
    ]
