# Generated by Django 4.2.6 on 2024-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_device_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceanalyzehistory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Create datetime'),
            preserve_default=False,
        ),
    ]
